### ISSUE TITLE
!set command fails silently

### ISSUE THREAD

**Issue by ErikMinekus** [nikersify/alfred-polyglot#1]
Steps to reproduce:
1. Open Alfred and type ```trans !set default-language ```
2. Pick a language and press Enter
3. The new language isn't stored

It looks like any output from update-config.js doesn't appear in Alfred's workflow debugger, so you can only see the error by running ```node update-config.js``` in Terminal. Basically this line is wrong:

```
const {env} = process.env
```

The correct code is either ```const {env} = process``` or ```const env = process.env```.

---

Also the documentation says: 
> Set the default language text will get translated to if ```from``` parameter is not specified.

But it sets the language for the ```to``` parameter, not the ```from``` parameter.

**Comment by nikersify** [comment]
Thank you!
