### ISSUE TITLE
Add a binary in the releases

### ISSUE THREAD

**Issue by vabatta** [nikersify/alfred-polyglot#2]
Hi, 

as the title please add a binary to the releases for people which don't use `npm`. 

Thanks!

**Comment by nikersify** [comment]
Done - would you mind letting me know whether it installs and works on your machine? I've tested it on my computer and it does, but just want to make sure I'm not missing anything.

Link to the release: https://github.com/nikersify/alfred-polyglot/releases/tag/v1.2.0

**Comment by vabatta** [comment]
Seems to work, I just feel it's kinda slow and power hungry with a nodejs script under the hood.

**Comment by nikersify** [comment]
I've measured the time it takes to run the script with input that doesn't need network requests and it's giving me around 0.2s from the time the script starts and when it ends on my machine.

I bet you could get that time way down by using a language that allows for precompilation, but personally I'm not interested in rewriting the workflow in as it is fast enough for me :)

Thanks for testing the file!
